### ISSUE TITLE
Peek vs. AUBI

### ISSUE THREAD

**Issue by snpdev** [Microsoft/peek#29]
Greetings,

As a CSP, the company I work for is excited by the possibilities of Peek.  We have also been introduced recently to a similar Microsoft project on GitHub, Azure Usage and Billing Insights (AUBI) Portal - https://github.com/Microsoft/AzureUsageAndBillingPortal.

I am interested in knowing if the Peek programmers are familiar with AUBI and how they view it relative to Peek.

Thanks - Mike

**Comment by harleenkohli** [comment]
thanks @snpdev. thanks for your query!

As of today, the underlying APIs which AUBI connects to are different from peek's. The azure APIs which provide usage and billing info in general are not available for CSP specific subscriptions - they are black listed. This was one of the original motivations behind building peek because our team caters specifically to CSPs and the tools available at the time were not able to get data from CSPs. At the moment, looks like AUBI will not work for CSPs, but this could change based on this thread - https://github.com/Microsoft/AzureUsageAndBillingPortal/issues/36

Another point of difference, since we tailor made the solution for CSPs, using this you can create separate power bi dashboards - for CSPs vs Customer's consumption - plus reports you will see here will be much more useful (or will require less rework). In near future, we will also include separate dashboards for indirect (2-T) scenarios. @UtkarshVIT can comment more on this.

Third, this solution can also be used for EAs - again the difference is that this solution is connecting to EA APIs rather than Azure usage APIs, so the data that you will see is more streamlined towards what EA admin should see.

Hope this solution helps your business need!

**Comment by snpdev** [comment]
Harleen, thank you very much for the quick reply to my post.  The information you have shared will help us focus our attention.  Specifically, as a CSP our needs are to have 1) a CSP portal for BI insights into the consumption and costs of our customers, and 2) a customer-centric portal into which each of our customers can log in and see BI filtered for their subscriptions.

We will convey our experiences with Peek here, but feel free to let me know if there is a more appropriate forum.

Thanks again - Mike

**Comment by UtkarshVIT** [comment]
@snpdev Unfortunately, GitHub does not have a discussion forum yet. However, in case of any bug or feature request you can always open a new issue. In case you have any suggestions on how we can create a discussion on this please let us know. 

Thanks 
Utkarsh Sharma
