### ISSUE TITLE
Where are the offline deployment binaries for FTP deployment option

### ISSUE THREAD

**Issue by ssugar** [Microsoft/peek#30]
Deployment guide has the line below in the Data Extraction Service API section, but I'm unsure where the source code link is, and I'm unable to find the "OfflineDeploymentBinaries" folder anywhere in the github code repository.

"For deployment via FileZilla FTP Client: From the source code link, copy the “BillingDataApi” folder from “OfflineDeploymentBinaries” folder to local computer."

**Comment by harleenkohli** [comment]
Thanks for your query @ssugar 
Yes, you are correct. We need to update the deployment guide as we no longer include offline deployment binaries in the code repository. Since the code is open source now, we recommend that the solution be built by the user at their end with proper configurations (and changes if any) and they generate their own offline deployment binaries. Once the solution is built successfully, the instructions in the deployment guide for offline deployment would remain the same. 

@UtkarshVIT - please update the offline deployment section to reflect this.

**Comment by ssugar** [comment]
Thanks for the prompt response @harleenkohli - I had gone ahead, updated the configs, and ran a rebuild on the API and WebJob projects in Visual Studio.  I've got the whole thing working now for our EA and CSP subscriptions which is very cool, except for the CSPUsage part of the API timing out (another issue is opened for that)

Very cool project, thanks so much!

**Comment by UtkarshVIT** [comment]
Hi! We have updated the APIs and you can now see the new code in the branch CSPUsageAsync([here](https://github.com/Microsoft/peek/tree/CSPUsageAsync)). Do test it and let us know your review
